{% set name = "opentelemetry-instrumentation-writer" %}
{% set version = "0.49.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_writer-{{ version }}.tar.gz
  sha256: 48fe04a57021d80155283f57aa11e3ec5d0e58f4b34d3aedf29fe2eaaf330159

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions-ai >=0.4.12,<0.5

test:
  imports:
    - opentelemetry.instrumentation.writer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - writer-sdk

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Writer instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
